language: julia
julia:
- nightly
- 1.3.0
os:
- windows
- linux
- osx
before_install:
- openssl aes-256-cbc -K $encrypted_07b4fc4562a4_key -iv $encrypted_07b4fc4562a4_iv
  -in config.enc -out config -d
after_success:
- julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
codecov: true
